#world_name: hospital_test_amcl
world_name: tue_hallway_RLtoAL
#world_name: brsu

plugins:
  - name: laser_integration
    lib: libed_laser_plugin_tracking.so
    frequency: 30
    parameters:
        laser_topic: /ropod/laser/scan
        min_segment_size_pixels: 6
        world_association_distance: 0.2
        segment_depth_threshold: 0.08
        min_cluster_size: 0.05
        max_cluster_size: 10.0
        max_gap_size: 1
        min_gap_size_for_split: 15
        check_door_status: 1
        nominal_corridor_width: 0.5
        correctRot: 1
        correctTrans: 0
        dist_for_object_split: 0.4
  - name: entity_clearer
    lib: libed_clearer_plugin.so
    enabled: 1
    parameters:
        entity_timeout: 3.0
  - name: gui_server
    lib: libed_gui_server_plugin.so     
    parameters:
        predict_entities: 0
